language: ruby
cache: bundler
rvm:
- 2.6.2
install:
- gem install bundler
- bundle install
script:
- bundle exec rake test
deploy:
  provider: rubygems
  gem: cookiefilter
  gemspec: cookiefilter.gemspec
  on:
    tags: true
    rvm: 2.6.2
  api_key:
    secure: cYqzGgSVQ/CCn359o0Et0xnGIZH5sjYERXq8hrzZVl2NjcrdU5BDbIbyRqhSNE9uXyLyADLDBSEHhMk5ce+8eO81dkQ75a/i7MUGtg0d3YWvZt+VqXFi0LdRr661eGRdIh4uj1yF4NCp+gP+9fotafQ2wKLnDRomCfXG5BU+flWWd31mozw29E4OR0+s3ya7IihBVU10g316jLTUDhAKgagsklUrc/JkmXnt/6JRdsA9adux/dut+HYqMAbCz2UlPhVvPExRsY/Vxk800W7ucWAdGcnkUIPq9FpxGjiW/JZzRqJb/0L1OMipINaTUALoJDpOAw0KD5xOcrNJATuvDImEaLHrK6kv6OJ4xkLLBVJPwxR+QpfAZnkrLFQRwkbj4jDrC0oBI8SVwMHGmpUQclY1SmGSR3BISYoI3osRi3Ku5f+QBKJBwgyd/3uAOc74fT9c86LjHfntyseB6R+Ieo83K+ADpLkBlCXzxnZ76nMrwhmN7gH9kluy0CrsDPYipLhd7xrbtSsIE62Uxz/ai3vcF6mUfy2RhGKo8FWcvJtxLPLlTluVci7nF8TVZhb3J7S+cmDe1nADDhaWtZ2ty0Gg1wW/+T+i8yEOBTJ9jh8nTwPIuqI712vHMJ1ac8YJRsRXrWniFUbX4txqVg/RxpvTXsSqHBzd1TaRa/vsIvM=
